### ISSUE TITLE
[Beginner-Friendly] Contribute to Hello Rube

### ISSUE THREAD

**Issue by DaylightFox** [DaylightFox/HelloRube#2]
Contribute to Hello Rube by adding a [Rube Goldberg Machine](https://en.wikipedia.org/wiki/Rube_Goldberg_machine)-esque implementation of the classic ["Hello World" script](https://en.wikipedia.org/wiki/%22Hello,_World!%22_program).

This can be done in any language you want, and in any complexity you want ranging from simple to wildly complex/convoluted.

Make sure to tell us about your code in your PR ;)

Feel free to browse what others have contributed for inspiration. If you have any ideas, feel free to leave them as a comment to help others get started.

**Comment by ivanelianto** [comment]
I've add C# version of Rail Rube :)

**Comment by anmol27katyani** [comment]
@DaylightFox Do you want me to add for some more languages?

**Comment by DaylightFox** [comment]
Feel free @octamois :)

**Comment by DaylightFox** [comment]
Closing this issue for the new 2018 Hacktoberfest :)
