### ISSUE TITLE
[Beginner Friendly] Hello Rube is back!

### ISSUE THREAD

**Issue by DaylightFox** [DaylightFox/HelloRube#34]
We're back at it again with Hacktoberfest 2018!

This project is for anyone of any skill level to contribute to. It's a fun little project to make a script in a language of your choice say "Hello World!". It can be as complicated as you like, so long as the end result is "Hello World!" ;)

The basis of this project is from the [Rube Goldberg Machine](https://en.wikipedia.org/wiki/Rube_Goldberg_machine), to make something so simple happen in a complicated and roundabout way.

So what are you waiting for? Get contributing! Make sure to tell us about your code in your PR :)

If you have any ideas, feel free to leave them as comments below to help people get started. And feel free to check out other people's contributions to the project.

**Comment by jacquesdev** [comment]
This sounds really amazing, going to give this a try. May even try to pass the data along to different language scripts to keep it fun :)

**Comment by DaylightFox** [comment]
> This sounds really amazing, going to give this a try.

Thanks! I love doing this project!

> May even try to pass the data along to different language scripts to keep it fun :)

That'll be interesting, go for it!

**Comment by silvericarus** [comment]
I'd love to try to get creative with this.

**Comment by silvericarus** [comment]
I have a problem when cloning the repo, the folder named "Moo:Cow" returns an invalid character and interrupts the process of cloning halfway though. Could this be fixed please?

**Comment by jacquesdev** [comment]
Feel to free to add your Hello World input to my JavaScript file https://github.com/DaylightFox/HelloRube/blob/master/Javascript/elloWorld.js and get it to increase the complexity of your Rube machine :)

**Comment by Henddher** [comment]
Hi @DaylightFox 

Nice initiative!

How do the PRs count toward [Hacktoberfest](https://hacktoberfest.digitalocean.com/)?

Do they get **labeled**? How?

**Comment by DaylightFox** [comment]
Hi @Henddher 

>Nice initiative!

Thanks!

>How do the PRs count toward Hacktoberfest?
>Do they get labeled? How?

So long as you've connected your Github account to Hacktoberfest then you're good to go! They track any and all PRs you make. So all you need to do is contribute :)

You can see your progress [here](https://hacktoberfest.digitalocean.com/stats/Henddher) (Specific to you)

**Comment by Henddher** [comment]
> You can see your progress [here](https://hacktoberfest.digitalocean.com/stats/Henddher) (Specific to you)

Wow ... apparently someone (👉 ![](https://avatars2.githubusercontent.com/u/3991010?s=88&v=4)) didn't read the instructions ?!

Thanks a lot @DaylightFox .... real fun!

**Comment by DaylightFox** [comment]
Thank you to everyone for participating this year, it's been great! I hope everyone has learnt a lot about open source software, version control and programming :)

I'll see you all next year!
